# Generated by Django 4.1.6 on 2023-02-12 03:59

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('adminstration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='administrators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(help_text="admin's first name", max_length=20, verbose_name='first name')),
                ('lname', models.CharField(help_text="admin's last name", max_length=20, verbose_name='last name')),
                ('username', models.CharField(blank=True, help_text="admin's user name", max_length=50, verbose_name='username')),
                ('email', models.EmailField(help_text="admin's email", max_length=254, unique=True, verbose_name='email')),
                ('date_registered', models.DateField(auto_now_add=True, verbose_name='date registered')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('password', models.CharField(max_length=50, null='false', verbose_name='password')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
