# Generated by Django 4.1.6 on 2023-02-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstration', '0003_administrator_delete_administrators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='password',
            field=models.CharField(max_length=100, null='false', verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='password',
            field=models.CharField(max_length=100, null='false', verbose_name='password'),
        ),
    ]
